baseURL = 'https://oregonhousingproject.org/'
languageCode = 'en-us'
title = 'Oregon Housing Project'
theme = 'hugo-book'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  BookSection = '/'
